# Generated by Django 4.1.9 on 2023-05-14 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=255)),
                ('vacancy_description', models.TextField()),
                ('company', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('add_date', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=250)),
            ],
        ),
    ]
